version: '3'
services:
  mongodb:
    image: mongo
    container_name: mongodb_new

    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db

  express:
    build: ./express  # ชี้ไปยังโฟลเดอร์ express ที่มี Dockerfile
    container_name: express_app_new
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/ESP32

  nginx:
    build: ./nginx
    container_name: nginx_new
    ports:
      - "80:80"
    depends_on:
      - express